### ISSUE TITLE
"Create New Feed" file upload with upload selection -- icon and text are not centered in window

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#131] opened 2020-10-14 14:47 UTC

**Comment by mairin** [comment] 2021-04-07 18:20
@Zoey-dev is working on this one, but for some reason I am unable to assign it to her.

**Comment by Zoey-dev** [comment] 2021-04-07 20:28
Hello, can i get a little more description on this?

**Comment by mairin** [comment] 2021-04-08 19:46
@Zoey-dev it looks like this one somehow got fixed in the meanwhile (neither myself or Jennings could reproduce) so I am just going to close it out. Sorry for the confusion!

**Closed by mairin** 2021-04-08 19:46 UTC

**Comment by Zoey-dev** [comment] 2021-04-08 22:34
Its fine. Thanks
