### ISSUE TITLE
Pagination Bug on UI

### ISSUE THREAD

**Issue by SkyC0der** [FNNDSC/ChRIS_ui#687] opened 2022-10-13 12:37 UTC
When there are no records displayed, Pagination section still displays showing (0 - 5 of -1). It should display No items available or shouldnt be displayed at all. Image Below. I would like to work on this
![issue](https://user-images.githubusercontent.com/44367769/195597885-092e9f9f-3e7b-4c70-9915-a33254204b17.jpeg)

**Comment by ciradu2204** [comment] 2022-10-13 13:35
can i work with you on this issue?

**Comment by SkyC0der** [comment] 2022-10-13 14:01
Sure. I noticed another Bug in the same "Create A New Analysis" modal page. In No. 3 "Select Plugin". The User should only be able to select one. Could you make the CheckBox Buttons to be Radio Buttons instead. There's an image below
![issue2](https://user-images.githubusercontent.com/44367769/195617986-7e35e8d5-9b2c-4929-899d-063cef04b962.jpeg)

**Comment by Jolzyfx** [comment] 2022-10-14 17:15
> Sure. I noticed another Bug in the same "Create A New Analysis" modal page. In No. 3 "Select Plugin". The User should only be able to select one. Could you make the CheckBox Buttons to be Radio Buttons instead. There's an image below ![issue2](https://user-images.githubusercontent.com/44367769/195617986-7e35e8d5-9b2c-4929-899d-063cef04b962.jpeg

@SkyC0der  I'm Interested in collaborating with you on this project

**Comment by jennydaman** [comment] 2022-10-17 03:35
> Sure. I noticed another Bug in the same "Create A New Analysis" modal page. In No. 3 "Select Plugin". The User should only be able to select one. Could you make the CheckBox Buttons to be Radio Buttons instead. There's an image below
> ![issue2](https://user-images.githubusercontent.com/44367769/195617986-7e35e8d5-9b2c-4929-899d-063cef04b962.jpeg)

Please create a separate issue for this.

**Comment by jennydaman** [comment] 2022-10-17 03:37
Duplicate of #686, @SkyC0der @ciradu2204 @Jolzyfx please carry on the discussion there.

**Closed by jennydaman** 2022-10-17 03:37 UTC
