### ISSUE TITLE
Convert Class Components into Function Components.

### ISSUE THREAD

**Issue by PintoGideon** [FNNDSC/ChRIS_ui#206] opened 2021-03-31 15:40 UTC
There a few class components that can be re-written into function components for a cleaner API.

List of the components that need to be re-written will be added here shortly.

**Comment by Deek9399** [comment] 2021-04-01 05:57
Hello, I am an outreachy applicant. I would like to work on this issue.

**Comment by PintoGideon** [comment] 2021-04-01 21:12
Hey @Deek9399 , Welcome to the project.

If you navigate from the root folder to the layout folder (src/containers/Layout), you will see a few components that need to be rewritten using hooks for a cleaner api. 
```
Header.tsx
PageWrapper.tsx
Sidebar.tsx
Toolbar.tsx
```

Let me know if you would like to take that up as a task and I'll assign this issue to you. Feel free to ask me any questions.

**Comment by somya51p** [comment] 2021-04-02 05:34
@PintoGideon If this issue is not assigned to @Deek9399, I wish to work on the same.

**Comment by Deek9399** [comment] 2021-04-02 06:07
@PintoGideon You can assign this issue to @somya51p. I am getting myself familiar with the project. If the issue is still available, I will check back again.

**Comment by PintoGideon** [comment] 2021-04-02 13:34
Hi @somya51p , This issue is now assigned to you. Feel free to reach out with any questions.

**Comment by somya51p** [comment] 2021-04-02 15:52
Yeah sure, ThankYou!

**Comment by Aaishpra** [comment] 2021-04-09 15:21
Hey, @jennydaman @PintoGideon I see no updates, can I take this up?

**Comment by PintoGideon** [comment] 2021-04-09 15:33
Hey @somya51p , Any update on this ?

**Comment by somya51p** [comment] 2021-04-09 15:41
@somya51p I had started working, just need some time.

**Comment by PintoGideon** [comment] 2021-04-09 16:41
No worries @somya51p

**Closed** 2021-04-15 13:00 UTC
Labels: good first issue
