### ISSUE TITLE
pac lookup filter ui

### ISSUE THREAD

**Issue by AndroGenius-codes** [FNNDSC/ChRIS_ui#647] opened 2022-10-10 13:31 UTC
-sign in
-click on pacs query/retrieve
-click on "more options"
- under filters when you click on date the UI is bad.  when you click on the year increment button it moves your cursor to bottom of screen
[screen-capture (1).webm](https://user-images.githubusercontent.com/70571088/194877719-a939c2e2-287a-40cc-aa3a-ee57cbd52133.webm)

**Comment by AndroGenius-codes** [comment] 2022-10-10 13:35
@jennydaman @mairin can i take a stab at fixing this

**Comment by codeEmpress1** [comment] 2022-10-10 18:24
@AndroGenius-codes yes it does.

**Comment by codeEmpress1** [comment] 2022-10-10 18:33
![image](https://user-images.githubusercontent.com/47438585/194931145-292e9479-0633-4eff-972e-d5238170206c.png)
The date field overflowing in this image and the other marked issues are what my PR fixed. I will go ahead and unlink this issue from mine. Sorry for the inconvenience. I am however open to collaboration to work with you on this calendar/year issue. Thank you.

**Comment by AndroGenius-codes** [comment] 2022-10-10 18:50
No problem

**Comment by jennydaman** [comment] 2022-10-12 06:05
@AndroGenius-codes did you have a PR for this? If not, no rush!

**Comment by AndroGenius-codes** [comment] 2022-10-12 09:01
> @AndroGenius-codes did you have a PR for this? If not, no rush!

Yes I already created a pull request. Tagged you to it too

**Comment by jennydaman** [comment] 2022-10-19 06:28
duplicate of https://github.com/FNNDSC/ChRIS_ui/issues/653

**Closed by jennydaman** 2022-10-19 06:28 UTC
