### ISSUE TITLE
Custom messages for backend error codes

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#222] opened 2021-04-09 03:41 UTC
Error codes, e.g. `CODE01`, are provided to explain why jobs are cancelled.

https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/d2ed29ef95c390f7b04ea5e56d61cbd19929135e/chris_backend/plugininstances/services/manager.py#L144

**Comment by zrthxn** [comment] 2021-04-13 10:03
Are these error codes returned in the HTTP response? From the file you link it looks like they're being logged to the console.

**Comment by jennydaman** [comment] 2021-04-13 21:33
They are returned in the http response.

Good observation. I did a search on the codebase for what the codes are (because I don't know where they're documented.)

You can try producing `CODE01`, either with fast fingers, or a simple script. I think it'll trigger if you try cancelling a plugin immediately after submitting it to run.

**Comment by Zoey-dev** [comment] 2021-04-14 14:44
@jennydaman hello, is this issue about displaying error messages from the back end on the front end?

**Comment by jennydaman** [comment] 2021-04-14 23:06
@Zoey-dev correct

**Comment by Zoey-dev** [comment] 2021-04-14 23:16
Okay, could you assign this task to me?

**Comment by Zoey-dev** [comment] 2021-04-14 23:19
Thanks

**Comment by Zoey-dev** [comment] 2021-04-16 10:25
@jennydaman hello, I'm thinking of making use of toast for this task.
What do you think?

**Comment by jennydaman** [comment] 2021-04-16 10:31
Toasts are like a temporary notification, though these errors happen and are permanent.

Maybe the error should be reported in the terminal window, or appear in a pop-up when clicking on the node details.

**Comment by Zoey-dev** [comment] 2021-04-16 19:31
Hmm, okay.

**Comment by Zoey-dev** [comment] 2021-04-19 09:23
@jennydaman Hi, I'm having a little difficulty understanding what to do. I don't understand the source of the error and where to expect them. Do they occur as a result of http requests, if yes is there a mock up screen for how the message should be displayed.

**Comment by jennydaman** [comment] 2021-04-20 20:01
We don't have any mockups for this feature, it would be up to your creativity.

The error codes are not a result of http requests, but instead backend errors, e.g. if the backend for whatever reason is unable to run a job.

Please try running `pl-is-broken`, which should cause an error message.

**Comment by Zoey-dev** [comment] 2021-04-22 12:21
@jennydaman  please is it possible to schedule a call?

**Comment by PintoGideon** [comment] 2021-04-22 14:45
Hi @Zoey-dev , Sorry for the delay in response from my end. I have listed down the steps to reproduce this issue. I am assuming that you have an UI instance up and have it pointing to the correct api endpoint.

**Step 1:**

Assuming you have access to a feed, you can add a node that finishes with the cancelled state. I am listing down the steps to do that , but you should already see a node with a cancelled status to work with.

![Step_1](https://user-images.githubusercontent.com/15992276/115732523-0d43e380-a356-11eb-898b-d7f24abbf716.png)

**Step 2:** 

Click on `'Add a Child Node'` and select `'pl-is-broken'`.

![Step_2](https://user-images.githubusercontent.com/15992276/115732525-0d43e380-a356-11eb-843e-53d775405b6d.png)

**Step 3:**

Click `'Next'` for all intermediary steps, and click on `'Add a Node'`.

![step_3](https://user-images.githubusercontent.com/15992276/115732514-0cab4d00-a356-11eb-9ad7-f54c4f2dd692.png)

**Step 4:**


![step_4](https://user-images.githubusercontent.com/15992276/115732515-0cab4d00-a356-11eb-85c9-9cae93002842.png)

**Step 5:**

![step_5](https://user-images.githubusercontent.com/15992276/115732517-0cab4d00-a356-11eb-85e5-b306b8dd9482.png)

**Step 6:**

![step_6](https://user-images.githubusercontent.com/15992276/115732520-0d43e380-a356-11eb-9aea-1d22cffd9d92.png)

Once the plugin is added, you see that it cancels out. If you navigate to the `'NodeDetails.tsx'` component and do a `console.log(selectedPlugin)`, you can see that the payload provides us with an `'error_code'` descriptor. 

This issue is a bit more involved. As you can see from the screenshot below, it's difficult to know what "`CODE10"` (the value of error_code) really means. You will have to look in the cube backend for the corresponding meaning behind each code and create a lookup table in the frontend. 

For example:
 `[CODE02]: Error getting job status at pfcon `
 
 Whenever, the Frontend see the error_code with the value, `CODE02`, it shows the corresponding message instead. As you see, this issue is a bit more involved. 


![Final_Step](https://user-images.githubusercontent.com/15992276/115732509-0cab4d00-a356-11eb-98a0-8271584d56c6.png)


Also, the next question is where to show the error message in the frontend. That's yet to be decided.

**Comment by jennydaman** [comment] 2021-04-23 04:40
@PintoGideon that is super useful.

@Zoey-dev my schedule has some gaps but it's a bit messy. When works for you? Please reach out on slack.
https://slack.babymri.org

**Comment by Zoey-dev** [comment] 2021-04-29 15:41
Hi @PintoGideon so this issue is a bit more challenging than i thought. So maybe you could help work me through my thought process. I am trying to use Error boundaries, you know. Create an Error boundary then wrap the code around it to capture these errors and display them. But then i would need this errors in one place or something. 

What do you think?

**Comment by PintoGideon** [comment] 2021-05-04 14:43
Hey @Zoey-dev , Sorry I missed out on this. We don't need an error boundary here. Error Boundaries are usually used to catch JavaScript errors inside components which corrupt React’s internal state and cause it to emit cryptic errors on next renders.

The error to be displayed in our case occurs when the execution of the plugin fails. The plugin's status changes to 'finishedWithError' or 'cancelled'. Once we see that status, we can check the error code and display the error. Let me know if that makes sense,

**Comment by Zoey-dev** [comment] 2021-05-07 15:59
Hey @PintoGideon so i have followed all the steps and i am not getting any error message on my end. Let me share a screenshot of the what i am getting


![Screenshot 2021-05-07 at 4 55 09 PM](https://user-images.githubusercontent.com/59091045/117477147-8d249d00-af55-11eb-9f59-d390c3528bcd.png)

**Closed** 2021-05-17 23:08 UTC
Labels: enhancement, good first issue
