### ISSUE TITLE
Image viewer is not consistent with images of various resolutions

### ISSUE THREAD

**Issue by Sandip117** [FNNDSC/ChRIS_ui#674] opened 2022-10-12 19:47 UTC
When using the image viewer from the feed view, the viewer breaks while rendering images with higher resolutions

**Comment by PintoGideon** [comment] 2022-10-12 21:05
Could you please provide screenshots since "breaks" could mean a lot of things  and also steps to reproduce this issue ? Also what are the resolutions of the images you use so that someone can test it using stock images with the same resolution.

**Comment by haszankauna** [comment] 2022-10-13 07:27
hello @Sandip117  can you please provide a more detailed description and if possible an image that shows the error you're getting

**Comment by haszankauna** [comment] 2022-10-13 07:28
Hello @PintoGideon  can I please be assigned to this?

**Comment by Sandip117** [comment] 2022-10-13 13:56
![image](https://user-images.githubusercontent.com/32147904/195614554-0e2b9dbc-429a-4bc2-924e-2ccfc84b2373.png)
The image that I used above to test has a resolution 1024 X 512

It seems like the image viewer currently can only render images of resolution 256 x 256. Anything higher than that is cropped before being rendered.

**Comment by haszankauna** [comment] 2022-10-19 08:46
@jennydaman will look into it

**Closed** 2024-04-03 00:10 UTC
Labels: bug, good first issue
