### ISSUE TITLE
Add new node wizard

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/ChRIS_ui#117] opened 2020-10-05 17:27 UTC
![Screenshot from 2020-10-06 11-03-24](https://user-images.githubusercontent.com/799683/95258436-c5170680-07f3-11eb-852c-145f860e5e32.png)
![Screenshot from 2020-10-06 11-04-11](https://user-images.githubusercontent.com/799683/95257654-a3694f80-07f2-11eb-90f0-e9b601532f05.png)

The main UI observation here is wiring up the "enter" key:

Configure Form:

- [ ]  Add subtext: `Use the "Add more parameters" button to add command line flags and values to the plugin. Note, if you prefer a free form input box where you might all the command line parameters together, you can safely hit "next" here.`
- [ ] Wire up "enter" to automatically give a "choose a parameter" dropdown.

**Comment by rudolphpienaar** [comment] 2020-10-05 17:30
The main UI observation here is wiring up the "enter" key:

Configure Form:

* Add subtext:

Use the "Add more parameters" button to add command line flags and values to the plugin. Note, if you prefer a free form input box where you might all the command line parameters together, you can safely hit "next" here.

* Wire up "enter" to automatically give a "choose a parameter" dropdown.

**Comment by rudolphpienaar** [comment] 2020-10-05 17:31
In the editor form:

* Wire up "enter" to automatically hit "next"

**Comment by mairin** [comment] 2020-10-07 19:24
(The deleted comment was just a dupe of the head comment, copy/pasted it over so it'd show up in the kanban)

**Comment by mairin** [comment] 2020-10-07 20:11
One of the things we talked about for the full editor form for plugin parameters was whether or not users might want to use the "Enter" key for carriage return here to indent / space out their parameter list and whether or not Enter == Next might be confusing for that case. So I think for the first form no doubt we should make the changes. I think for the full editor one, we should think a little more on how to streamline it and see if there's an alternative to enter in the editor window. (E.g. maybe something like Shift+Enter gets you to the next button on each screen, it's not something you'd hit accidentally or would conflict with a common pattern like Enter == carriage return in a text edit window, but for power users it's a way to speed up their workflow.)

**Closed** 2020-10-16 19:01 UTC
